### PR TITLE
Materials for my (Jacob Hummel) first Ask an Astronomer post.

### PR DESCRIPTION
**Pull request by hummel**
I included an image to top the post along with a thumbnail, but feel free to swap them out if you think of something better!

### CODE REVIEW

**Comment by stefano-meschiari** [comment]
Thanks, I pushed the post with a couple small changes. I changed the  paths from absolute to relative so that I could preview it on localhost. Everything else looks great, thank you for taking the time to do it!

**Comment by jmsilverman** [comment]
The 2nd to last and 3rd to last paragraphs are the same...

--Jeff

On Sat, Dec 19, 2015 at 1:14 PM, Stefano Meschiari <notifications@github.com

**Comment by stefano-meschiari** [comment]
Oh wow, good catch, I'll take care of it.

**Comment by hummel** [comment]
Oops.  Thanks for catching that Jeff!

Oh wow, good catch, I'll take care of it.

**Pull request merged**
